name: Deployment to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build
        working-directory: ./backend
        env:  
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          npm install
          cd src && npx prisma generate  
          npm run build  

      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./backend/dist/*"
          target: "${{ secrets.PATH }}"

      - name: Create .env file on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ${{ secrets.PATH }}/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ${{ secrets.PATH }}/.env
            echo "PORT=${{ secrets.PORT }}" >> ${{ secrets.PATH }}/.env
            cd ${{ secrets.PATH }}
            pm2 reload all || pm2 start server.js --name "my-backend"
